CREATE DATABASE IF NOT EXISTS crud
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE crud;

CREATE TABLE IF NOT EXISTS concerts (
    id INT(11) NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    place VARCHAR(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    date DATE DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
